// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCMXe7yRrF0NuGTnbJwjB3fI7aE-lqakw',
    appId: '1:820117834791:web:a29477b54c17f4598d1202',
    messagingSenderId: '820117834791',
    projectId: 'gymapp-8a4d2',
    authDomain: 'gymapp-8a4d2.firebaseapp.com',
    storageBucket: 'gymapp-8a4d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkJt7sbomwM8sYliX_OuSbcYtONmpT1Y',
    appId: '1:820117834791:android:61fb96756e1c48a38d1202',
    messagingSenderId: '820117834791',
    projectId: 'gymapp-8a4d2',
    storageBucket: 'gymapp-8a4d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2phYCNbN_adITJByMxyHPguXPARFmZ2E',
    appId: '1:820117834791:ios:80e3c735002e28ff8d1202',
    messagingSenderId: '820117834791',
    projectId: 'gymapp-8a4d2',
    storageBucket: 'gymapp-8a4d2.appspot.com',
    iosClientId: '820117834791-k2fqoc0knibo4mbif9bfi6cqujfurmn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2phYCNbN_adITJByMxyHPguXPARFmZ2E',
    appId: '1:820117834791:ios:80e3c735002e28ff8d1202',
    messagingSenderId: '820117834791',
    projectId: 'gymapp-8a4d2',
    storageBucket: 'gymapp-8a4d2.appspot.com',
    iosClientId: '820117834791-k2fqoc0knibo4mbif9bfi6cqujfurmn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymapp',
  );
}
